
import { UserSettings, AppLanguage } from './types';

export const DEFAULT_SETTINGS: UserSettings = {
  reminderInterval: 60,
  startTime: "08:00",
  endTime: "22:00",
  notificationsEnabled: false,
  language: 'vi'
};

export const STORAGE_KEY = 'hydroflow_settings_v1';

export const LANGUAGES: { code: AppLanguage, name: string, flag: string }[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' }
];

export const TRANSLATIONS: Record<AppLanguage, any> = {
  en: {
    reminders: "Reminders",
    active: "Active",
    off: "Off",
    blocked: "Blocked",
    start: "Start",
    end: "End",
    frequency: "Frequency",
    mins: "mins",
    save: "Save Schedule",
    applied: "Applied",
    notifTitle: "Settings Saved!",
    notifBody: "Your water reminders are now active.",
    remindTitle: "Time to drink water!",
    remindBody: "Drink a glass of water now to stay healthy.",
    nextReminder: "Next reminder in",
    testNotif: "Test Notification",
    testSuccess: "It works! You will see notifications like this.",
    outsideHours: "Outside active hours",
    howToFix: "How to enable?",
    fixInstruction: "Click the lock icon (🔒) or 3 dots and allow 'Notifications'.",
    install: "Install",
    installDesc: "For stable notifications"
  },
  vi: {
    reminders: "Nhắc nhở",
    active: "Đang hoạt động",
    off: "Đang tắt",
    blocked: "Bị chặn",
    start: "Bắt đầu",
    end: "Kết thúc",
    frequency: "Tần suất",
    mins: "phút",
    save: "Lưu lịch nhắc nhở",
    applied: "Đã áp dụng",
    notifTitle: "Đã lưu cài đặt!",
    notifBody: "Lịch nhắc uống nước của bạn đã được kích hoạt.",
    remindTitle: "Đã đến lúc uống nước!",
    remindBody: "Uống một ly nước ngay để cơ thể luôn khỏe mạnh.",
    nextReminder: "Nhắc nhở sau",
    testNotif: "Thử thông báo",
    testSuccess: "Tuyệt vời! Bạn sẽ nhận được thông báo như thế này.",
    outsideHours: "Ngoài giờ hoạt động",
    howToFix: "Cách bật lại?",
    fixInstruction: "Bấm vào biểu tượng ổ khóa (🔒) hoặc 3 chấm và cho phép 'Thông báo'.",
    install: "Cài đặt",
    installDesc: "Để thông báo ổn định hơn"
  },
  es: {
    reminders: "Recordatorios",
    active: "Activo",
    off: "Apagado",
    blocked: "Bloqueado",
    start: "Inicio",
    end: "Fin",
    frequency: "Frecuencia",
    mins: "min",
    save: "Guardar Horario",
    applied: "Aplicado",
    notifTitle: "¡Ajustes Guardados!",
    notifBody: "Tus recordatorios de agua ya están activos.",
    remindTitle: "¡Hora de beber agua!",
    remindBody: "Bebe un vaso de agua ahora para mantenerte sano.",
    nextReminder: "Próximo aviso en",
    testNotif: "Probar Notificación",
    testSuccess: "¡Funciona! Verás notificaciones como esta.",
    outsideHours: "Fuera de horario",
    howToFix: "¿Cómo activar?",
    fixInstruction: "Haz clic en el candado (🔒) y permite 'Notificaciones'.",
    install: "Instalar",
    installDesc: "Para avisos estables"
  },
  fr: {
    reminders: "Rappels",
    active: "Actif",
    off: "Désactivé",
    blocked: "Bloqué",
    start: "Début",
    end: "Fin",
    frequency: "Fréquence",
    mins: "min",
    save: "Enregistrer",
    applied: "Appliqué",
    notifTitle: "Paramètres enregistrés!",
    notifBody: "Vos rappels d'eau sont maintenant actifs.",
    remindTitle: "C'est l'heure de boire!",
    remindBody: "Buvez un verre d'eau pour rester en forme.",
    nextReminder: "Prochain rappel",
    testNotif: "Tester",
    testSuccess: "Ça marche ! Vous recevrez des rappels ainsi.",
    outsideHours: "Hors créneau",
    howToFix: "Comment activer ?",
    fixInstruction: "Cliquez sur le cadenas (🔒) et autorisez les 'Notifications'.",
    install: "Installer",
    installDesc: "Pour des rappels stables"
  },
  de: {
    reminders: "Erinnerungen",
    active: "Aktiv",
    off: "Aus",
    blocked: "Blockiert",
    start: "Start",
    end: "Ende",
    frequency: "Häufigkeit",
    mins: "Min",
    save: "Speichern",
    applied: "Gespeichert",
    notifTitle: "Einstellungen gespeichert!",
    notifBody: "Deine Wasser-Erinnerungen sind nun aktiv.",
    remindTitle: "Zeit zum Wassertrinken!",
    remindBody: "Trink jetzt ein Glas Wasser, um gesund zu bleiben.",
    nextReminder: "Nächste Erinnerung",
    testNotif: "Testen",
    testSuccess: "Es funktioniert! So sehen deine Erinnerungen aus.",
    outsideHours: "Außerhalb der Zeit",
    howToFix: "Wie aktivieren?",
    fixInstruction: "Klicke auf das Schloss (🔒) und erlaube 'Benachrichtigungen'.",
    install: "Installieren",
    installDesc: "Für stabile Erinnerungen"
  },
  zh: {
    reminders: "提醒",
    active: "已开启",
    off: "已关闭",
    blocked: "已屏蔽",
    start: "开始时间",
    end: "结束时间",
    frequency: "频率",
    mins: "分钟",
    save: "保存设置",
    applied: "已保存",
    notifTitle: "设置已保存！",
    notifBody: "喝水提醒现已生效。",
    remindTitle: "该喝水了！",
    remindBody: "现在喝杯水，保持身体健康。",
    nextReminder: "下次提醒倒计时",
    testNotif: "测试通知",
    testSuccess: "测试成功！您将收到此类通知。",
    outsideHours: "非活跃时段",
    howToFix: "如何开启？",
    fixInstruction: "点击锁图标 (🔒) 并允许“通知”。",
    install: "安装",
    installDesc: "以获得更稳定的提醒"
  },
  ja: {
    reminders: "リマインダー",
    active: "有効",
    off: "無効",
    blocked: "ブロック中",
    start: "開始",
    end: "終了",
    frequency: "頻度",
    mins: "分",
    save: "保存する",
    applied: "保存済み",
    notifTitle: "設定を保存しました！",
    notifBody: "水分補給リマインダーが有効になりました。",
    remindTitle: "お水を飲む時間です！",
    remindBody: "健康のために今すぐお水を一杯飲みましょう。",
    nextReminder: "次のリマインダー",
    testNotif: "通知テスト",
    testSuccess: "成功！このような通知が届きます。",
    outsideHours: "時間外",
    howToFix: "設定方法は？",
    fixInstruction: "鍵アイコン (🔒) をクリックして「通知」を許可してください。",
    install: "インストール",
    installDesc: "通知を安定させるために"
  },
  ko: {
    reminders: "알림",
    active: "활성화",
    off: "비활성화",
    blocked: "차단됨",
    start: "시작",
    end: "종료",
    frequency: "빈도",
    mins: "분",
    save: "일정 저장",
    applied: "적용됨",
    notifTitle: "설정이 저장되었습니다!",
    notifBody: "이제 물 마시기 알림이 활성화되었습니다.",
    remindTitle: "물 마실 시간이에요!",
    remindBody: "건강을 위해 지금 물 한 잔을 마셔보세요.",
    nextReminder: "다음 알림까지",
    testNotif: "알림 테스트",
    testSuccess: "성공! 이런 방식으로 알림을 받게 됩니다.",
    outsideHours: "활동 시간 아님",
    howToFix: "활성화 방법?",
    fixInstruction: "자물쇠 아이콘(🔒)을 클릭하고 '알림'을 허용하세요.",
    install: "설치",
    installDesc: "안정적인 알림을 위해"
  },
  ar: {
    reminders: "التذكيرات",
    active: "نشط",
    off: "متوقف",
    blocked: "محظور",
    start: "البداية",
    end: "النهاية",
    frequency: "التكرار",
    mins: "دقيقة",
    save: "حفظ الجدول",
    applied: "تم الحفظ",
    notifTitle: "تم حفظ الإعدادات!",
    notifBody: "تذكيرات شرب الماء نشطة الآن.",
    remindTitle: "حان وقت شرب الماء!",
    remindBody: "اشرب كوبًا من الماء الآن للبقاء بصحة جيدة.",
    nextReminder: "التذكير القادم خلال",
    testNotif: "اختبار الإشعار",
    testSuccess: "يعمل! ستصلك إشعارات مثل هذه.",
    outsideHours: "خارج ساعات العمل",
    howToFix: "كيفية التفعيل؟",
    fixInstruction: "انقر على أيقونة القفل (🔒) واسمح بـ 'الإشعارات'.",
    install: "تثبيت",
    installDesc: "لإشعارات أكثر استقراراً"
  },
  pt: {
    reminders: "Lembretes",
    active: "Ativo",
    off: "Desligado",
    blocked: "Bloqueado",
    start: "Início",
    end: "Fim",
    frequency: "Frequência",
    mins: "min",
    save: "Salvar Horário",
    applied: "Aplicado",
    notifTitle: "Definições Salvas!",
    notifBody: "Seus lembretes de água estão ativos.",
    remindTitle: "Hora de beber água!",
    remindBody: "Beba um copo de água agora para manter a saúde.",
    nextReminder: "Próximo lembrete em",
    testNotif: "Testar Notificação",
    testSuccess: "Funciona! Você receberá avisos assim.",
    outsideHours: "Fora do horário",
    howToFix: "Como ativar?",
    fixInstruction: "Clique no cadeado (🔒) e permita 'Notificações'.",
    install: "Instalar",
    installDesc: "Para avisos estáveis"
  }
};
